name: CI Build

on: [push, pull_request]

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.1
        with:
          concurrent_skipping: 'same_content'
          paths_ignore: '[".github/CODEOWNERS"]'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  ROOT5:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build with Docker
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=ghcr.io/star-bnl/star-sw-root5-base@sha256:bc73379c552ff02181d9c6778ff64bece4f11c5a2aaf75fd23cd62d9af6b8349
          push: false
          tags: ghcr.io/star-bnl/star-sw-root5-build
          file: docker/Dockerfile.root5

  ROOT6:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build with Docker
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=ghcr.io/star-bnl/star-sw-root6-base@sha256:9b40544fa0af6ac911eddeaa396b04bab5e78da0ebef36170e779269c177e9f9
          push: false
          tags: ghcr.io/star-bnl/star-sw-root6-build
          file: docker/Dockerfile.root6
